despesa/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from despesa.views import (
    DetalheDespesa,
    DetalheDespesaPeca,
    DetalheDespesaProduto,
    ListaCategoriaDespesa,
    ListaDespesa,
    apagarcategoriadespesa,
    apagardespesa,
    cadastrarcategoriadespesa,
    cadastrardespesa,
    editarcatergoriadespesa,
    editardespesa,
)

urlpatterns = [
    path('despesa/', login_required(ListaDespesa.as_view()), name='despesa'),
    path('categoriadespesa/', login_required(cadastrarcategoriadespesa), name='categoria-despesa'),
    path('cadastrardespesa/', login_required(cadastrardespesa), name='cadastrar-despesa'),
    path('editardespesa/<int:pk>/', login_required(editardespesa), name='editar-despesa'),
    path('apagardespesa/<int:pk>/', login_required(apagardespesa), name='apagar-despesa'),
    path('listacategoriadespesa/', login_required(ListaCategoriaDespesa.as_view()), name='lista-categoria-despesa'),
    path('apagarcategoriadespesa/<int:pk>/', login_required(apagarcategoriadespesa), name='apagar-categoria-despesa'),
    path('editarcategoriadespesa/<int:pk>/', login_required(editarcatergoriadespesa), name='editar-categoria-despesa'),
    path(
        'detalhedespesaproduto/<int:pk>/',
        login_required(DetalheDespesaProduto.as_view()),
        name='detalhe-despesa-produto',
    ),
    path('detalhedespesapeca/<int:pk>/', login_required(DetalheDespesaPeca.as_view()), name='detalhe-despesa-peca'),
    path('detalhedespesa/<int:pk>/', login_required(DetalheDespesa.as_view()), name='detalhe-despesa'),
]

erp/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('produto.urls')),
    path('', include('dashboard.urls')),
    path('', include('venda.urls')),
    path('', include('peca.urls')),
    path('', include('cliente.urls')),
    path('', include('colaborador.urls')),
    path('', include('despesa.urls')),
    path('', include('financeiro.urls')),
    path('', include('relatorio.urls')),
    path('', include('configuracao.urls')),
    path('', include('orcamento.urls')),
    path('', include('usuarios.urls')),
    path('', include('fornecedor.urls')),
    path('', include('comunidade.urls')),
    path('', include('suporte.urls')),
    path('', include('pedido.urls')),
    path('', include('lanhouse.urls')),  

]

despesa/models.py
from django.contrib.auth.models import User
from django.db import models

from fornecedor.models import Fornecedores


class CategoriaDespesa(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.PROTECT)
    nome_categoria_despesa = models.CharField(max_length=100)

    def __str__(self) -> str:
        return self.nome_categoria_despesa


class Despesa(models.Model):
    PIX = 'Pix'
    CARTAO_CREDITO = 'Cartāo de credito'
    CARTAO_DEBITO = 'Cartāo de debito'
    DINHEIRO = 'Dinheiro'
    FIADO = 'Fiado a pagar'
    FORMA_PAGAMENTO = [
        (PIX, 'Pix'),
        (CARTAO_CREDITO, 'Cartāo de credito'),
        (CARTAO_DEBITO, 'Cartāo de debito'),
        (DINHEIRO, 'Dinheiro'),
        (FIADO, 'Fiado a pagar'),
    ]

    usuario = models.ForeignKey(User, on_delete=models.PROTECT)
    categoria_despesa = models.ForeignKey(CategoriaDespesa, on_delete=models.CASCADE, null=True, blank=True)
    nome_despesa = models.CharField(max_length=90)
    preco_despesa = models.DecimalField(max_digits=9, decimal_places=2)
    fornecedor = models.ForeignKey(Fornecedores, on_delete=models.CASCADE, null=True, blank=True)
    observacao = models.TextField(max_length=1000, null=True, blank=True)
    data_cadastro = models.DateTimeField(auto_now_add=True, editable=False)
    forma_pagamento = models.CharField(choices=FORMA_PAGAMENTO, max_length=17, default=PIX)
    data_vencimento = models.DateField(null=True, blank=True)
    qtd_parcela = models.IntegerField(null=True, blank=True)
    valor_entrada = models.DecimalField(max_digits=9, decimal_places=2, null=True, blank=True)

    def saldodespesa(self):
        return self.preco_despesa - self.valor_entrada

despesa/forms.py
from django import forms

from despesa.models import CategoriaDespesa, Despesa
from fornecedor.models import Fornecedores


class CategoriaDespesaForms(forms.ModelForm):
    class Meta:
        model = CategoriaDespesa
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(CategoriaDespesaForms, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
        self.fields['usuario'].widget = forms.HiddenInput()


class DespesaForms(forms.ModelForm):
    class Meta:
        model = Despesa
        fields = '__all__'
        widgets = {
            'observacao': forms.TextInput(),
        }

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        super(DespesaForms, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

        self.fields['usuario'].widget = forms.HiddenInput()

        self.fields['fornecedor'].queryset = Fornecedores.objects.filter(usuario=user)
        self.fields['categoria_despesa'].queryset = CategoriaDespesa.objects.filter(usuario=user)

despesa/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.views.generic import DetailView, ListView

from despesa.forms import CategoriaDespesaForms, DespesaForms
from despesa.models import CategoriaDespesa, Despesa
from peca.models import Pecas
from produto.models import Produto


class ListaDespesa(ListView):
    model = Despesa
    template_name = 'despesa/pagina-inicial-despesa.html'
    context_object_name = 'object'

    def get_queryset(self):
        return Despesa.objects.filter(usuario=self.request.user)

    def get_context_data(self, **kwargs):
        context = super(ListaDespesa, self).get_context_data(**kwargs)
        context['peca'] = Pecas.objects.filter(forma_pagamento='Fiado a pagar', usuario=self.request.user)
        context['produto'] = Produto.objects.filter(forma_pagamento='Fiado a pagar', usuario=self.request.user)
        return context


@login_required
def cadastrardespesa(request):
    template_name = 'despesa/formularios/formulario-cadastrar-despesa.html'
    form = DespesaForms(request.POST or None, initial={'usuario': request.user}, user=request.user)

    if request.method == 'POST':
        if form.is_valid():
            despesa = form.save()
            template_name = 'despesa/tabela/linhas-tabela-despesa.html'

            context = {'object': despesa}
            return render(request, template_name, context)

    context = {'form': form}
    return render(request, template_name, context)


@login_required
def editardespesa(request, pk):
    template_name = 'despesa/formularios/formulario-editar-despesa.html'
    instance = Despesa.objects.get(pk=pk)
    form = DespesaForms(request.POST or None, instance=instance, initial={'usuario': request.user}, user=request.user)

    if instance.usuario != request.user:
        raise PermissionError

    if request.method == 'POST':
        if form.is_valid():
            despesa = form.save()
            template_name = 'despesa/tabela/linhas-tabela-despesa.html'
            context = {'object': despesa}

            return render(request, template_name, context)

    context = {'form': form, 'object': instance}
    return render(request, template_name, context)


@login_required
def apagardespesa(request, pk):
    template_name = 'despesa/tabela/tabela-despesa.html'
    obj = Despesa.objects.get(pk=pk)
    if obj.usuario == request.user:
        obj.delete()
    else:
        raise PermissionError
    return render(request, template_name)


@login_required
def cadastrarcategoriadespesa(request):
    template_name = 'despesa/formularios/formulario-categoria-despesa.html'
    form = CategoriaDespesaForms(request.POST or None, initial={'usuario': request.user})

    if request.method == 'POST':
        if form.is_valid():
            template_name = 'despesa/tabela/linha-categoria-despesa.html'
            categoria_despesa = form.save()
            context = {'object': categoria_despesa}
            return render(request, template_name, context)

    context = {'form': form}
    return render(request, template_name, context)


@login_required
def apagarcategoriadespesa(request, pk):
    template_name = 'despesa/tabela/categoria-despesa.html'
    obj = CategoriaDespesa.objects.get(pk=pk)
    if obj.usuario == request.user:
        obj.delete()
        return render(request, template_name)
    else:
        raise PermissionError


class ListaCategoriaDespesa(ListView):
    model = CategoriaDespesa
    template_name = 'despesa/tabela/tabela-categoria-despesa.html'
    context_object_name = 'object'

    def get_queryset(self):
        return CategoriaDespesa.objects.filter(usuario=self.request.user)


@login_required
def editarcatergoriadespesa(request, pk):
    template_name = 'despesa/formularios/formulario-editar-categoria-despesa.html'
    instance = CategoriaDespesa.objects.get(pk=pk)
    form = CategoriaDespesaForms(request.POST or None, initial={'usuario': request.user}, instance=instance)
    if instance.usuario != request.user:
        raise PermissionError
    if request.method == 'POST':
        if form.is_valid():
            template_name = 'despesa/tabela/linha-categoria-despesa.html'
            categoria_despesa = form.save()
            context = {'object': categoria_despesa}
            return render(request, template_name, context)

    context = {'form': form, 'object': instance}
    return render(request, template_name, context)


class DetalheDespesaProduto(DetailView):
    model = Produto
    template_name = 'despesa/off-canvas/canvas-despesa-produto.html'


class DetalheDespesaPeca(DetailView):
    model = Pecas
    template_name = 'despesa/off-canvas/canvas-despesa-peca.html'


class DetalheDespesa(DetailView):
    model = Despesa
    template_name = 'despesa/off-canvas/canvas-despesa.html'

despesa/templates/despesa/formularios/formulario-cadastrar-despesa.html
{% load widget_tweaks %}
<div class="modal-header">
  <h5 class="modal-title" id="exampleModalToggle"> Cadastrar despesa </h5>
  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
  </button>
</div>
<form hx-post="{% url 'cadastrar-despesa' %}" hx-target="#despesa-Tbody" hx-indicator=".htmx-indicator"
      hx-swap="afterbegin">

  <div class="modal-body">
    {% csrf_token %}
    <div class="row g-2" style="margin-bottom: 10px;">
      <div class="col form-floating">
        {% render_field form.usuario class="form-control" %}
        {% render_field form.nome_despesa class="form-control" %}
        <label for="">Descrição da despesa </label>
      </div>
      <div class="col form-floating">
        {% render_field form.categoria_despesa class="form-select" %}
        <label for="">Informe a categoria desta despesa (opcional)</label>
      </div>
    </div>
    <!---->
    <div class="row g-2" style="margin-bottom: 10px;">
      <div class="col-3 form-floating">
        {% render_field form.preco_despesa class="form-control" value="0.00" %}
        <label for="">Informe o preco da despesa</label>
      </div>
      <div class="col-3 form-floating">
        {% render_field form.forma_pagamento class="form-select" %}
        <label for="">Forma de pagamento</label>
      </div>
      <div class="col-6 form-floating">
        {% render_field form.fornecedor class="form-select" %}
        <label for="">Informe o fornecedor se houver(opcional)</label>
      </div>
    </div>
    <!---->
    <div class="row g-2" style="margin-bottom: 10px;">
      <div class="col form-floating">
        {% render_field form.observacao class="form-control" %}
        <label for="">Informe observação se houver</label>
      </div>
    </div>
    <div class="row g-2" style="color: #FFFFFF;">
      <div class="col-6  form-floating">
        {% render_field form.valor_entrada class="form-control" value="0.00" type="hidden" %}
        <label id="label_valor_entrada">Valor de entrada</label>
      </div>
      <div class="col-3 form-floating">
        {% render_field form.qtd_parcela class="form-control" value="01" type="hidden" %}
        <label id="label_qtd_parcela">Qtd. parcela</label>
      </div>
      <div class="col-3 form-floating">
        {% render_field form.data_vencimento class="form-control" type="hidden" %}
        <label id="label_data_vencimento">Data vencimento</label>
      </div>
    </div>
  </div>


  <div class="modal-footer">
    <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Cancelar</button>
    <button type="submit" class="btn btn-outline-primary">Finalizar</button>
  </div>
</form>

<script>

  document.querySelector('#id_forma_pagamento').addEventListener('change', function () {
    var valor_entrada = document.querySelector('#id_valor_entrada');
    var data_vencimento = document.querySelector('#id_data_vencimento');
    var qtd_parcela = document.querySelector('#id_qtd_parcela');
    var label_valor_entrada = document.querySelector('#label_valor_entrada');
    var label_data_vencimento = document.querySelector('#label_data_vencimento')
    var label_qtd_parcela = document.querySelector('#label_qtd_parcela')



    if (this.value === "Fiado a pagar") {
      valor_entrada.setAttribute('type', 'Number');
      data_vencimento.setAttribute('type', 'Date');
      qtd_parcela.setAttribute('type', 'Number');
      label_valor_entrada.style.color = "rgb(67, 67, 67)";
      label_data_vencimento.style.color = "rgb(67, 67, 67)";
      label_qtd_parcela.style.color = "rgb(67, 67, 67)"
    }
    else {
      valor_entrada.setAttribute('type', 'Hidden');
      data_vencimento.setAttribute('type', 'Hidden');
      qtd_parcela.setAttribute('type', 'Hidden');
      label_valor_entrada.style.color = "#FFFFFF";
      label_data_vencimento.style.color = "#FFFFFF";
      label_qtd_parcela.style.color = "#FFFFFF";
    }
  });

  $('form').on('submit', function () {
    $('#staticBackdrop').modal('toggle')
    setTimeout(() => {
      $('#success_tic').modal('toggle')
    }, 500)
  });
</script>

despesa/templates/despesa/formularios/formulario-categoria-despesa.html
<div class="modal-header">
  <h5 class="modal-title" id="exampleModalToggle"> Cadastrar Categoria </h5>
  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">

  </button>
</div>
<form
  hx-post="{% url 'categoria-despesa' %}"
  hx-indicator=".htmx-indicator">

  <div class="modal-body">
    {% csrf_token %}
    {{ form }}
  </div>

  <div class="modal-footer">
    <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Cancelar</button>
    <button type="submit" class="btn btn-outline-primary">Finalizar</button>
  </div>
</form>


<script>
  $('form').on('submit', function() {
    $('#staticBackdrop').modal('toggle')
  });
</script>

despesa/templates/despesa/formularios/formulario-editar-categoria-despesa.html
<div class="modal-header">
  <h5 class="modal-title" id="exampleModalToggle"> Cadastrar Categoria </h5>
  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">

  </button>
</div>
<form
  hx-post="{% url 'editar-categoria-despesa' object.pk %}"
  hx-target="#tr-Categoria{{ object.pk }}"
  hx-swap = "outerHTML"
  hx-indicator=".htmx-indicator">

  <div class="modal-body">
    {% csrf_token %}
    {{ form }}
  </div>

  <div class="modal-footer">
    <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Cancelar</button>
    <button type="submit" class="btn btn-outline-primary" data-bs-target="#staticBackdrop" data-bs-toggle="modal">Finalizar</button>
  </div>
</form>


<script>
  $('form').on('submit', function() {
    $('#staticBackdrop').modal('toggle')
  });
</script>

despesa/templates/despesa/formularios/formulario-editar-despesa.html
{% load widget_tweaks %}
<div class="modal-header">
  <h5 class="modal-title" id="staticBackdropLabel">Editar {{object.nome_despesa}}</h5>
  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">

  </button>
</div>
<form hx-post="{% url 'editar-despesa' object.pk %}" hx-target="#despesaTr{{ object.pk }}"
      hx-indicator=".htmx-indicator" hx-swap="outerHTML">

  <div class="modal-body">
    {% csrf_token %}
    <div class="row g-2" style="margin-bottom: 10px;">
      <div class="col form-floating">
        {% render_field form.usuario class="form-control" %}
        {% render_field form.nome_despesa class="form-control" %}
        <label for="">Descrição da despesa </label>
      </div>
      <div class="col form-floating">
        {% render_field form.categoria_despesa class="form-select" %}
        <label for="">Informe a categoria desta despesa (opcional)</label>
      </div>
    </div>
        <!---->
    <div class="row g-2" style="margin-bottom: 10px;">
      <div class="col-3 form-floating">
        {% render_field form.preco_despesa class="form-control" value="0.00" %}
        <label for="">Informe o preco da despesa</label>
      </div>
      <div class="col-3 form-floating">
        {% render_field form.forma_pagamento class="form-select" %}
        <label for="">Forma de pagamento</label>
      </div>
      <div class="col-6 form-floating">
        {% render_field form.fornecedor class="form-select" %}
        <label for="">Informe o fornecedor se houver(opcional)</label>
      </div>
    </div>
        <!---->
    <div class="row g-2" style="margin-bottom: 10px;">
      <div class="col form-floating">
        {% render_field form.observacao class="form-control" %}
        <label for="">Informe observação se houver</label>
      </div>
    </div>
    <div class="row g-2">
      <div class="col-6  form-floating">
        {% render_field form.valor_entrada class="form-control" value="0.00"  %}
        <label id="label_valor_entrada">Valor de entrada</label>
      </div>
      <div class="col-3 form-floating">
        {% render_field form.qtd_parcela class="form-control" value="01" %}
        <label id="label_qtd_parcela">Qtd. parcela</label>
      </div>
      <div class="col-3 form-floating">
        {% render_field form.data_vencimento class="form-control" %}
        <label id="label_data_vencimento">Data vencimento</label>
      </div>
    </div>
  </div>

  <div class="modal-footer">
    <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Cancelar</button>
    <button type="submit" class="btn btn-outline-primary">Finalizar</button>
  </div>
</form>
<script>
  $('form').on('submit', function () {
    $('#staticBackdrop').modal('toggle')
    setTimeout(() => {
      $('#success_tic_editar').modal('toggle')
    }, 500)
  });
  document.querySelector('#id_forma_pagamento').addEventListener('change', function () {
    var valor_entrada = document.querySelector('#id_valor_entrada');
    var data_vencimento = document.querySelector('#id_data_vencimento');
    var qtd_parcela = document.querySelector('#id_qtd_parcela');
    var label_valor_entrada = document.querySelector('#label_valor_entrada');
    var label_data_vencimento = document.querySelector('#label_data_vencimento')
    var label_qtd_parcela = document.querySelector('#label_qtd_parcela')



    if (this.value === "Fiado a pagar") {
      valor_entrada.setAttribute('type', 'Number');
      data_vencimento.setAttribute('type', 'Date');
      qtd_parcela.setAttribute('type', 'Number');
      label_valor_entrada.style.color = "rgb(67, 67, 67)";
      label_data_vencimento.style.color = "rgb(67, 67, 67)";
      label_qtd_parcela.style.color = "rgb(67, 67, 67)"
    }
    else {
      valor_entrada.setAttribute('type', 'Hidden');
      data_vencimento.setAttribute('type', 'Hidden');
      qtd_parcela.setAttribute('type', 'Hidden');
      label_valor_entrada.style.color = "#FFFFFF";
      label_data_vencimento.style.color = "#FFFFFF";
      label_qtd_parcela.style.color = "#FFFFFF";
    }


  });
</script>