erp/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('produto.urls')),
    path('', include('dashboard.urls')),
    path('', include('venda.urls')),
    path('', include('peca.urls')),
    path('', include('cliente.urls')),
    path('', include('colaborador.urls')),
    path('', include('despesa.urls')),
    path('', include('financeiro.urls')),
    path('', include('relatorio.urls')),
    path('', include('configuracao.urls')),
    path('', include('orcamento.urls')),
    path('', include('usuarios.urls')),
    path('', include('fornecedor.urls')),
    path('', include('comunidade.urls')),
    path('', include('suporte.urls')),
    path('', include('pedido.urls')),
    path('', include('lanhouse.urls')),  

]

pedido/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from pedido.views import DetalhePedido, ListaPedido, apagarpedido, cadastrarpedido, editarpedido

urlpatterns = [
    path('cadastrarpedido', login_required(cadastrarpedido), name='cadastrar-pedido'),
    path('editarpedido/<int:pk>/', login_required(editarpedido), name='editar-pedido'),
    path('apagarpedido/<int:pk>/', login_required(apagarpedido), name='apagar-pedido'),
    path('pedido', login_required(ListaPedido.as_view()), name='pedido'),
    path('detalhepedido/<int:pk>/', DetalhePedido.as_view(), name='detalhe-pedido'),
]

pedido/models.py
from django.contrib.auth.models import User
from django.db import models

from cliente.models import Cliente


class Pedido(models.Model):
    ENTREGUE = 'Entregue'
    CANCELADA = 'Cancelada'
    PROCESSAMENTO = 'Em processo'
    STATUS = [
        (ENTREGUE, 'Concluida e entregue'),
        (CANCELADA, 'Cancelada e estornada'),
        (PROCESSAMENTO, 'Em processo'),
    ]
    usuario = models.ForeignKey(User, on_delete=models.PROTECT)
    data_criacao = models.DateTimeField(auto_now_add=True)
    data_edicao = models.DateTimeField(auto_now=True)
    cliente = models.ForeignKey(Cliente, on_delete=models.PROTECT)
    produto = models.CharField(max_length=100)
    valor_produto = models.DecimalField(max_digits=9, decimal_places=2)
    data_entrega = models.DateField()
    valor_pago = models.DecimalField(max_digits=9, decimal_places=2)
    observacao = models.TextField(null=True, blank=True)
    status = models.CharField(choices=STATUS, max_length=20, default=PROCESSAMENTO)

    def valor_a_receber(self):
        return self.valor_produto - self.valor_pago

pedido/forms.py
from django import forms

from cliente.models import Cliente
from pedido.models import Pedido


class PedidoForms(forms.ModelForm):
    class Meta:
        model = Pedido
        fields = '__all__'

        widgets = {'valor_produto': forms.NumberInput(), 'observacao': forms.TextInput()}

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super(PedidoForms, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

        self.fields['usuario'].widget = forms.HiddenInput()
        self.fields['cliente'].queryset = Cliente.objects.filter(usuario=user)

pedido/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.views.generic import DetailView, ListView

from pedido.forms import PedidoForms
from pedido.models import Pedido


class ListaPedido(ListView):
    model = Pedido
    template_name = 'pedido/pagina-inicial-pedido.html'

    def get_queryset(self):
        return Pedido.objects.filter(usuario=self.request.user)


@login_required
def cadastrarpedido(request):
    template_name = 'pedido/formularios/form-cadastrar-pedido.html'
    form = PedidoForms(request.POST or None, initial={'usuario': request.user}, user=request.user)

    if request.method == 'POST':
        if form.is_valid():
            pedido = form.save()
            template_name = 'pedido/tabela/linha-tabela-pedido.html'
            context = {'object': pedido}
            return render(request, template_name, context)

    context = {'form': form}
    return render(request, template_name, context)


@login_required
def editarpedido(request, pk):
    template_name = 'pedido/formularios/form-editar-pedido.html'
    instance = Pedido.objects.get(pk=pk)
    form = PedidoForms(request.POST or None, instance=instance, initial={'usuario': request.user}, user=request.user)

    if instance.usuario != request.user:
        raise PermissionError

    if request.method == 'POST':
        if form.is_valid():
            template_name = 'pedido/tabela/linha-tabela-pedido.html'
            pedido = form.save()
            context = {'object': pedido}
            return render(request, template_name, context)

    context = {'form': form, 'object': instance}
    return render(request, template_name, context)


@login_required
def apagarpedido(request, pk):
    template_name = 'pedido/tabela/tabela-pedido.html'
    obj = Pedido.objects.get(pk=pk)

    if obj.usuario == request.user:
        obj.delete()
        return render(request, template_name)
    else:
        raise PermissionError


class DetalhePedido(DetailView):
    model = Pedido
    template_name = 'pedido/off-canvas/detalhe-pedido.html'

pedido/templates/pedido/formularios/form-cadastrar-pedido.html
{% load widget_tweaks %}


<div class="modal-header">
  <h5 class="modal-title fs-5" id="staticBackdropLabel">Cadastrar pedido</h5>
  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
</div>
<form hx-post="{% url 'cadastrar-pedido' %}" hx-target="#pedido-Tbody" hx-swap="afterbegin"
      hx-indicator=".htmx-indicator">
  <div class="modal-body">
    {% csrf_token %}
    <div class="row g-2" style="margin-bottom: 10px;">
      <div class="col form-floating">
        {% render_field form.usuario class='form-control' %}
        {% render_field form.produto class='form-control' %}
        {% render_field form.status class='form-control' %}
        <label for="">Informe o produto ou peça</label>
      </div>
      <div class="col form-floating">
        {% render_field form.valor_produto type="Number" value="00.00" %}
        <label for="">Informe o preço de venda</label>
      </div>
    </div>
    <div class="row g-2" style="margin-bottom: 10px;">
      <div class="col form-floating">
        {% render_field form.cliente class='form-select' %}
        <label for="">Informe o cliente</label>
      </div>
    </div>
    <div class="row g-2" style="margin-bottom: 10px;">
      <div class="col form-floating">
        {% render_field form.data_entrega class='form-control' type="date" %}
        <label for="">Data de entrega</label>
      </div>
      <div class="col form-floating">
        {% render_field form.valor_pago class='form-control' type="Number" value="00.00" %}
        <label for="">Valor pago</label>
      </div>
      <div class="row g-2" style="margin-bottom: 10px;">
        <div class="col form-floating">
          {% render_field form.observacao class="form-control" %}
          <label for="">Observaçāo</label>
        </div>
      </div>
    </div>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Cancelar</button>
    <button type="submit" class="btn btn-outline-primary">Salvar</button>
  </div>
</form>

<script>
  $('form').on('submit', function () {
    $('#staticBackdrop').modal('toggle')
    setTimeout(() => {
      $('#success_tic').modal('toggle');
    }, "500");
  });

  document.querySelector('#id_status').setAttribute('hidden', 'hidden')
</script>

pedido/templates/pedido/formularios/form-editar-pedido.html
{% load widget_tweaks %}
<div class="modal-header">
  <h5 class="modal-title fs-5" id="staticBackdropLabel">Editar pedido</h5>
  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
</div>
<form hx-post="{% url 'editar-pedido' object.pk %}" hx-target="#pedidoTr{{ object.pk }}" hx-swap="outerHTML"
      hx-indicator=".htmx-indicator">
  <div class="modal-body">
    {% csrf_token %}
    <div class="row g-2" style="margin-bottom: 10px;">
      {% render_field form.usuario class='form-control' %}
      <div class="col form-floating">
        {% render_field form.cliente class='form-select' %}
        <label for="">Informe o cliente</label>
      </div>
      <div class="col form-floating">
        {% render_field form.status class='form-select' %}
        <label for="">Informe a situacao</label>
      </div>
    </div>
    <div class="row g-2" style="margin-bottom: 10px;">
      <div class="col form-floating">

        {% render_field form.produto class='form-control' %}
        <label for="">Informe o produto ou peça</label>
      </div>
      <div class="col form-floating">
        {% render_field form.valor_produto class='form-control' type="Number" value="00.00" %}
        <label for="">Informe o preço de venda</label>
      </div>
    </div>

    <div class="row g-2" style="margin-bottom: 10px;">
      <div class="col form-floating">
        {% render_field form.data_entrega class='form-control' type="Date" %}
        <label for="">Data de entrega</label>
      </div>
      <div class="col form-floating">
        {% render_field form.valor_pago class='form-control' type="Number" value="00.00" %}
        <label for="">Valor pago</label>
      </div>
      <div class="row g-2" style="margin-bottom: 10px;">
        <div class="col form-floating">
          {% render_field form.observacao class="form-control" %}
          <label for="">Observaçāo</label>
        </div>
      </div>
    </div>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Cancelar</button>
    <button type="submit" class="btn btn-outline-primary">Salvar</button>
  </div>
</form>

<script>
  $('form').on('submit', function () {
    $('#staticBackdrop').modal('toggle')
    setTimeout(() => {
      $('#success_tic_editar').modal('toggle')
    }, "500");
  });
</script>